name: Fetch all

on:
  workflow_dispatch:

jobs:
  fetch_latest:
    name: Fetch from Harmonised API
    runs-on: ubuntu-latest
    env:
      IEC_HAPI_PROJ_PUBS_KEY: ${{ secrets.IEC_HAPI_PROJ_PUBS_KEY }}
      IEC_HAPI_PROJ_PUBS_SECRET: ${{ secrets.IEC_HAPI_PROJ_PUBS_SECRET }}
    steps:
      - uses: actions/checkout@master
      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Update gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Fetches latest updates
        run: |
          bundle exec ruby fetch_all.rb
          zip index.zip index.yaml
      - name: Push data
        run: |
          echo `date` > flag.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add flag.txt index.zip index.yaml
          find ./data -name '*' | xargs git add
          git diff --quiet && git diff --staged --quiet || (git commit --amend -m 'update documents' && git push -f)
